# Generated by Django 4.0.5 on 2022-06-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0002_alter_club_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='club.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='club.club')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['date'],
                'get_latest_by': 'date',
            },
        ),
    ]
